BidMe/src/java/view/CategoriesBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import boundary.CategoryFacade;
import entities.Category;
import java.util.List;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;

/**
 *
 * @author Roar, Sanaullah
 */
@Named(value = "categoriesBean")
@RequestScoped
public class CategoriesBean {

    @EJB
    private CategoryFacade categoryFacade;
    /**
     * Creates a new instance of CategoriesBean
     */
    public CategoriesBean() {
    }
    
    public List<Category> getCategories() {
        return categoryFacade.findAll();
    }
    
    public String getCategoryName(Long categoryId) {
        return categoryFacade.find(categoryId).getCategoryName();
    }
}

BidMe/src/java/view/CreateUserBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entities.BidMeUser;
import boundary.UserFacade;
import entities.Address;
import entities.PhoneNumber;
import javax.inject.Named;
import java.io.Serializable;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;

/**
 *
 * @author roar
 */
@Named(value = "createUserBean")
@RequestScoped
public class CreateUserBean implements Serializable {
    String firstName;
    String lastName;
    String username;
    String password;
    String street;
    String city;
    String postcode;
    String country;
    String phonePrefix;
    String phoneNumber;
    
    BidMeUser user;
    
   @EJB
    private UserFacade userFacade;
    
    public CreateUserBean() {
        this.user = new BidMeUser();
    }
    

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getPostcode() {
        return postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getPhonePrefix() {
        return phonePrefix;
    }

    public void setPhonePrefix(String phonePrefix) {
        this.phonePrefix = phonePrefix;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    
    public String postUser() {
        this.user.setUsername(this.username);
        this.user.setPassword(this.password);
        this.user.setFirstName(this.firstName);
        this.user.setLastName(this.lastName);
        Address adr = new Address();
        adr.setCity(city);
        adr.setCountry(country);
        adr.setPostcode(postcode);
        adr.setStreet(street);
        this.user.setAddress(adr);
        PhoneNumber pho = new PhoneNumber();
        pho.setCountryCode(Integer.parseInt(phonePrefix));
        pho.setLocalNumber(Integer.parseInt(phoneNumber));
        this.userFacade.create(this.user);
        return "createUserResponse?faces-redirect=true";
    }   
    
    
}

BidMe/src/java/view/LoginBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import boundary.LoggedInUserSessionBean;
import boundary.LoginException;
import entities.BidMeUser;
import java.io.Serializable;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

/**
 *
 * @author roar
 */
@Named(value = "loginBean")
@SessionScoped
public class LoginBean implements Serializable {
    @EJB
    private LoggedInUserSessionBean loggedInUserSB;

    String response;

    public String getResponse() {
        return response;
    }
    
    public String getLoggedInUserName() {
        return loggedInUserSB.getLoggedInUsername();
    }
    
    public String getLoggedInFullname() {
        BidMeUser user = loggedInUserSB.getLoggedInUser();
        if (user != null)
            return user.getFirstName() + " " + user.getLastName();
        return "";
    }
    
    public BidMeUser getLoggedInUser() {
        return loggedInUserSB.getLoggedInUser();
    }
    
    public void logout() {
        response = "User logged out";
        loggedInUserSB.logout();
    }
    
    public String login(String username, String password) {
        try {
            loggedInUserSB.login(username, password);
        }
        catch (LoginException e) {
            response = e.getMessage();
            return "login";
        }
        response = "User " + username + " logged in";
        return "index?faces-redirect=true";
    }
    
    public boolean isLoggedIn() {
        return loggedInUserSB.getLoggedInUser() != null;
    }
    
    /**
     * Creates a new instance of LoginBean
     */
    public LoginBean() {
    }
    
}

BidMe/src/java/view/ProductDetailsBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import boundary.ProductFacade;
import boundary.CategoryFacade;
import entities.Bid;
import entities.BidMeUser;
import entities.Category;
import entities.Product;
import java.time.LocalDateTime;
import java.time.format.DateTimeParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.Resource;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.jms.Connection;
import javax.jms.ConnectionFactory;
import javax.jms.JMSException;
import javax.jms.MessageProducer;
import javax.jms.Queue;
import javax.jms.Session;
import javax.jms.TextMessage;
import javax.jms.Topic;

/**
 *
 * @author Roar, Sanaullah
 */
@Named(value = "productDetailsBean")
@RequestScoped
public class ProductDetailsBean {
    private Long productId;
    private Product product;

    private String name;
    private String description;
    private LocalDateTime auctionStartDate;
    private LocalDateTime auctionEndDate;
    private Double startPrice;
    private String seller;
    private Long categoryId;
    
    @Inject
    private LoginBean loginBean;
    
    @EJB
    private CategoryFacade categoryFacade;
    
    @EJB
    private ProductFacade productFacade;

    @Resource(lookup = "jms/NotifyBuyerFactory")
    private ConnectionFactory connectionFactory;
    @Resource(lookup = "jms/NotifyBuyer")
    private Queue notifyBuyerQueue;
    @Resource(lookup = "jms/AuctionEndedFactory")
    private ConnectionFactory topicConnectionFactory;
    @Resource(lookup = "jms/AuctionEnded")
    private Topic auctionEndedTopic;

    /**
     * Creates a new instance of ProductDetailsBean
     */
    public ProductDetailsBean() {
    }

    public Double getCurrentBid() {
        if (productId == null)
            return 0.0;
        Bid highestBid = productFacade.getCurrentBid(productId);
        if (highestBid == null)
            return 0.0;
        return highestBid.getAmount();
    }

    public Long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    public String getSeller() {
        return seller;
    }

    public void setSeller(String seller) {
        this.seller = seller;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getAuctionStartDate() {
        return dateToString(auctionStartDate);
    }

    public void setAuctionStartDate(String auctionStartDate) {
        this.auctionStartDate = stringToDate(auctionStartDate);
    }

    public String getAuctionEndDate() {
        return dateToString(auctionEndDate);
    }

    public void setAuctionEndDate(String auctionEndDate) {
        this.auctionEndDate = stringToDate(auctionEndDate);
    }

    public Double getStartPrice() {
        return startPrice;
    }

    public void setStartPrice(Double startPrice) {
        this.startPrice = startPrice;
    }
    
    public void setProductId(Long productId) {
        this.productId = productId;
    }    

    public Long getProductId() {
        return productId;
    }
    
    public Product getProduct() {
        return product;
    }

    public void init() {
        if (productId != null) {
            product = productFacade.find(productId);
            updateProperties();
        }
    }

    public String postProduct() {
        boolean isNewProduct = productId == null;
        if (isNewProduct)
            product = new Product();
        else
            product = productFacade.find(productId);
        updateProductEntity();
        if (isNewProduct)
            productFacade.create(product);
        else
            productFacade.edit(product);
        return "viewProduct?faces-redirect=true&productId=" + product.getId().toString();
    }
    
    public String triggerAuctionEnd(Long productId) throws JMSException {
        Product triggerProduct = productFacade.find(productId);
        Bid highestBid = productFacade.getCurrentBid(productId);
        if (highestBid == null) {
            Logger.getLogger(ProductDetailsBean.class.getName()).log(Level.INFO, "Auction ended without any bidders\n");
            return "viewProduct?faces-redirect=true&productId=" + productId.toString();
        }
        
        BidMeUser winner = highestBid.getBidder();
        
        Connection connection = connectionFactory.createConnection(); 
        Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);
        MessageProducer queueProducer = session.createProducer(notifyBuyerQueue);
        TextMessage message = session.createTextMessage();
        message.setText("--- START EMAIL to customer " + winner.getUsername() + " ---\n"
            + "Dear " + winner.getFirstName() + "\n"
            + "Congratulations, you won the bid for product " + triggerProduct.getName() + "\n"
            + "Product URL: https://localhost:8181/faces/viewProduct?faces-redirect=true&productId=" + productId.toString() + "\n"
            + "--- END EMAIL ---"); 
        queueProducer.send(message);
        
        MessageProducer topicProducer = session.createProducer(auctionEndedTopic);
        TextMessage topicMessage = session.createTextMessage();
        topicMessage.setText("Auction for product id=" + triggerProduct.getName() + "ended"); 
        topicProducer.send(topicMessage);
                
        return "viewProduct?faces-redirect=true&productId=" + productId.toString();
    }
    
    private void updateProperties() {
        name = product.getName();
        description = product.getDescription();
        auctionStartDate = product.getAuctionStartDate();
        auctionEndDate = product.getAuctionEndDate();
        startPrice = product.getStartPrice();
        seller = product.getSeller().getUsername();
        categoryId = product.getCategory().getId();
    }
    
    private void updateProductEntity() {
        if (name != null)
            product.setName(name);
        if (description != null)
            product.setDescription(description);
        if (auctionStartDate != null)
            product.setAuctionStartDate(auctionStartDate);
        if (auctionEndDate != null)
            product.setAuctionEndDate(auctionEndDate);
        if (startPrice != null)
            product.setStartPrice(startPrice);
        BidMeUser sellerUser = loginBean.getLoggedInUser();
        if (sellerUser != null)
            product.setSeller(sellerUser);
        if (categoryId != null) {
            Category category = categoryFacade.find(categoryId);
            if (category != null)
                product.setCategory(category);
        }
    }

    private String dateToString(LocalDateTime date) {
        if (date == null)
            return "";
        return date.toString();
    }

    private static LocalDateTime stringToDate(String date) {
        try {
            return LocalDateTime.parse(date);
        }
        catch (DateTimeParseException e) {
            return LocalDateTime.now();
        }
    }
}

BidMe/web/auctionList.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
    </h:head>
    <h:body>
        <ui:composition template="commonLayout.xhtml">
            <ui:define name="title">Welcome</ui:define>
            <ui:define name="content">
                <ui:include src="searchBox.xhtml"/>
                <ul>
                    <ui:repeat value="#{productsBean.filteredList}" var="product">
                        <li>
                            <h:link value="#{product.name}" outcome="viewProduct">
                                <f:param name="productId" value="#{product.id}" />
                            </h:link>
                        </li>
                    </ui:repeat>
                </ul>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

BidMe/web/commonLayout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>BidMe: <ui:insert name="title"/></title>
    </h:head>
    <h:body>
        <div name="header">
            <ui:fragment rendered="#{loginBean.loggedIn}">
                <h:panelGrid columns="5">
                    <ui:fragment>BidMe</ui:fragment>
                    User: <h:outputText value="#{loginBean.loggedInFullname}"/>
                    <h:form>
                        <h:commandLink value="Log out" action="#{loginBean.logout()}"/>
                    </h:form>
                    <h:link value="Add Product" outcome="editProduct"/>
                </h:panelGrid>
            </ui:fragment>
            <ui:fragment rendered="#{not loginBean.loggedIn}">
                BidMe
                <h:link value="Log in" outcome="login.xhtml"/>
            </ui:fragment>
            <hr/>
        </div>
        <ui:insert name="content"/>
    </h:body>
</html>

BidMe/web/createUser.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
    </h:head>
    <h:body>
        <ui:composition template="commonLayout.xhtml">
            <ui:define name="title">Create new user</ui:define>
            <ui:define name="content">
                <h3>Create new user</h3>
                <h:form>
                    Username: <h:inputText id="userName" value="#{createUserBean.username}"/><br/>
                    Password: <h:inputText id="password" value="#{createUserBean.password}"/><br/>
                    FirstName: <h:inputText id="firstName" value="#{createUserBean.firstName}"/><br/>
                    LastName: <h:inputText id="lastName" value="#{createUserBean.lastName}"/><br/>
                    street: <h:inputText id="street" value="#{createUserBean.street}"/><br/>
                    Postcode: <inputText id="postcode" value="#createUserBean.postcode"/><br/>
                     City: <inputText id="city" value="#createUserBean.city"/><br/>
                      country: <inputText id="country" value="#createUserBean.country"/><br/>
                       PhonePrefix: <inputText id="phonePrefix" value="#createUserBean.phonePrefix"/><br/>
                        PhoneNumber: <inputText id="phoneNumber" value="#createUserBean.phoneNumber"/><br/>
                    <h:commandButton id="submit" value="submit" action="#{createUserBean.postUser()}" />
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

BidMe/web/createUserResponse.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:outputText value="#{createUserBean.username}"/>
    </h:body>
</html>

BidMe/web/editProduct.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <f:metadata>
        <f:viewParam name="productId" value="#{productDetailsBean.productId}"/>
        <f:viewAction action="#{productDetailsBean.init}" />
    </f:metadata>
    <h:head>
        <title>Edit product</title>
    </h:head>
    <h:body>
        <ui:composition template="commonLayout.xhtml">
            <ui:define name="title">Edit Product</ui:define>
            <ui:define name="content">
                <h:form>
                    <h:inputHidden id="productId" value="#{productDetailsBean.productId}"/>
                    Name: <h:inputText id="userName" value="#{productDetailsBean.name}"/><br/>
                    Description: <h:inputText id="description" value="#{productDetailsBean.description}"/><br/>
                    Start Date: <h:inputText id="auctionStartDate" value="#{productDetailsBean.auctionStartDate}"/><br/>
                    End Date: <h:inputText id="auctionEndDate" value="#{productDetailsBean.auctionEndDate}"/><br/>
                    Starting price: <h:inputText id="startPrice" value="#{productDetailsBean.startPrice}"/><br/>
                    Category: <h:selectOneMenu value="#{productDetailsBean.categoryId}">
                        <f:selectItems value="#{categoriesBean.categories}" var="category" itemValue="#{category.id}" itemLabel="#{category.categoryName}"/>
                    </h:selectOneMenu><br/>
                    <h:commandButton id="submit" value="Save" action="#{productDetailsBean.postProduct()}"/>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

BidMe/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title></title>
    </h:head>
    <h:body>
        <ui:composition template="commonLayout.xhtml">
            <ui:define name="title">Welcome</ui:define>
            <ui:define name="content">
                <h3>Welcome to BidMe</h3>
                <ui:include src="searchBox.xhtml"/>
                Auctions:
                <ul>
                    <ui:repeat value="#{productsBean.getProducts(10)}" var="product">
                        <li>
                            <h:link value="#{product.name}" outcome="viewProduct">
                                <f:param name="productId" value="#{product.id}" />
                            </h:link>
                        </li>
                    </ui:repeat>
                </ul>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

BidMe/web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
    </h:head>
    <h:body>
        <ui:composition template="commonLayout.xhtml">
            <ui:define name="title">Login</ui:define>
            <ui:define name="content">
                <h:form>
                    Username: <h:inputText id="userName" value="#{input1}"/><br/>
                    Password: <h:inputText id="password" value="#{input2}"/><br/>
                    <h:commandButton id="submit" value="Login" action="#{loginBean.login(input1, input2)}"/>
                </h:form>
                <!--form method="POST" action="j_security_check">
                    Username: <input type="text" name="j_username" />
                    Password: <input type="password" name="j_password" />
                    <br />
                    <input type="submit" value="Login" />
                    <input type="reset" value="Reset" />
                </form-->                
                Response: <h:outputText value="#{loginBean.response}"/><br/>
                <h:link outcome="createUser.xhtml" value="Create user"/>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

BidMe/web/loginError.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h2>Login Error</h2>
        Sorry, you made an Error. Please try again: <a href="#{facesContext.externalContext.requestContextPath}/" >Login</a>
    </h:body>
</html>

BidMe/web/loginResponse.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Login response</title>
    </h:head>
    <h:body>
        <h:outputText value="#{loginBean.response}"/>
    </h:body>
</html>

BidMe/web/searchBox.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
    </h:head>
    <h:body>
        <ui:composition>
            <h:form>
                Search: <h:inputText id="textFilter" value="#{productsBean.textFilter}"></h:inputText>
                <h:commandButton value="Search" action="#{productsBean.filterAuctions()}"></h:commandButton>
            </h:form>
        </ui:composition>
    </h:body>
</html>

BidMe/web/viewProduct.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <f:metadata>
        <f:viewParam name="productId" value="#{productDetailsBean.productId}" required="true"/>
        <f:viewAction action="#{productDetailsBean.init}" />
    </f:metadata>
    <h:head>
        <title>View Product</title>
    </h:head>
    <h:body>
        <ui:composition template="commonLayout.xhtml">
            <ui:define name="title"><h:outputText value="#{productDetailsBean.name}"/></ui:define>
            <ui:define name="content">
                <h3><h:outputText value="#{productDetailsBean.name}"/></h3>
                Description: <h:outputText value="#{productDetailsBean.description}"/><br/>
                Auction start time: <h:outputText value="#{productDetailsBean.auctionStartDate}"/><br/>
                Auction end time: <h:outputText value="#{productDetailsBean.auctionEndDate}"/><br/>
                Starting price: <h:outputText value="#{productDetailsBean.startPrice}"/><br/>
                Seller: <h:outputText value="#{productDetailsBean.seller}"/><br/>
                Category: <h:outputText value="#{categoriesBean.getCategoryName(productDetailsBean.categoryId)}"/><br/>
                Current Bid: <h:outputText value="#{productDetailsBean.currentBid}"/><br/>
                <h:link value="Edit Product" outcome="editProduct" rendered="#{loginBean.loggedIn and loginBean.loggedInUserName eq productDetailsBean.seller}">
                    <f:param name="productId" value="#{productDetailsBean.productId}" />
                </h:link>
                <h:form>
                    <h:commandButton id="submit" value="Trigger auction end" action="#{productDetailsBean.triggerAuctionEnd(productDetailsBean.productId)}"/>
                </h:form>
                <ui:fragment rendered="#{loginBean.loggedIn and loginBean.loggedInUserName ne productDetailsBean.seller}">
                    <br/>
                    <h:form>
                        <h:inputText id="bidAmount" value="#{bidBean.amount}"/>
                        <h:commandButton id="submit" value="Place bid" action="#{bidBean.postBid(productDetailsBean.productId)}"/>
                    </h:form>
                </ui:fragment>
            </ui:define>
        </ui:composition>
    </h:body>
</html>